### ISSUE TITLE
Windows updater fails when drivers loading 

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Edison-Image#5]
When I first tried the Windows batch file and plugged in the board, the drivers started installing and the update failed. After the drivers finished the next update worked fine. Maybe suggest they plug in the board and install drivers first? Windows 7

**Comment by jlucidar** [comment]
will note this on the wiki page for flashing on windows

**Comment by jlucidar** [comment]
modification done here : https://github.com/FabMo/FabMo-Engine/wiki/Flash-a-FabMo-Edison-Image-on-Windows
